from __future__ import annotations

"""为年报切块补充可过滤、可审计的报表语义元数据。

这里不调用 LLM，也不改变原始正文或表格矩阵。字段只从当前切块已经
存在的表头、行标签、章节路径和来源元数据中确定性推断；无法确定时
使用 ``unknown`` 或空值，避免把相似表格静默合并。
"""

from datetime import datetime
import re
from typing import Any, Mapping


_DATE_RE = re.compile(
    r"\b(January|February|March|April|May|June|July|August|September|October|November|December)\s+"
    r"(\d{1,2}),\s*(\d{4})\b",
    re.IGNORECASE,
)
_YEAR_RE = re.compile(r"\b(?:FY\s*)?(19|20)\d{2}\b", re.IGNORECASE)
_UNIT_RE = re.compile(
    r"(?:in|₹|rs\.?|rupees?|\$|usd|eur|€|jpy|¥)\s*"
    r"(?:us\s*)?(million|millions|billion|billions|thousand|thousands|crore|crores|"
    r"lakh|lakhs|百万|亿元|千元)\b",
    re.IGNORECASE,
)


_FAMILY_PATTERNS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "balance_sheet",
        (
            "balance sheet",
            "balance sheets",
            "statement of financial position",
            "financial position",
            "total assets",
            "total current assets",
            "total non-current assets",
            "total liabilities",
            "total shareholders",
            "total stockholders",
            "资产负债表",
            "资产总额",
            "负债总额",
        ),
    ),
    (
        "cash_flow",
        (
            "cash flow",
            "cash flows",
            "cash generated by operating",
            "cash used in financing",
            "cash from operating",
            "现金流",
            "经营活动产生",
            "投资活动产生",
            "融资活动产生",
        ),
    ),
    (
        "segment",
        (
            "business segment",
            "operating segment",
            "geographic segment",
            "geographical",
            "region",
            "regions",
            "products",
            "services",
            "net sales by",
            "revenue by",
            "收入结构",
            "业务分部",
            "地区分部",
        ),
    ),
    (
        "income_statement",
        (
            "income statement",
            "income statements",
            "statements of operations",
            "statements of income",
            "revenue from operations",
            "total net sales",
            "gross margin",
            "operating income",
            "net income",
            "profit before tax",
            "profit after tax",
            "净销售额",
            "营业收入",
            "净利润",
            "利润总额",
        ),
    ),
    (
        "equity",
        (
            "shareholders' equity",
            "shareholders’ equity",
            "stockholders' equity",
            "total equity",
            "retained earnings",
            "accumulated deficit",
            "common stock",
            "share repurchases",
            "股东权益",
            "留存收益",
            "股本",
        ),
    ),
    (
        "ratio",
        (
            "ratio analysis",
            "financial ratios",
            "gross margin percentage",
            "operating margin",
            "ebit margin",
            "earnings per share",
            "basic and diluted eps",
            " eps",
            "return on",
            "debt to equity",
            "比率分析",
            "利润率",
            "偿债能力",
        ),
    ),
    (
        "workforce",
        (
            "employees",
            "employee count",
            "headcount",
            "workforce",
            "attrition",
            "员工",
            "雇员",
            "人员",
        ),
    ),
    (
        "risk",
        (
            "risk factors",
            "principal risks",
            "market risk",
            "forward-looking statements",
            "risk management",
            "liquidity risk",
            "legal proceedings",
            "commitments and contingencies",
            "风险因素",
            "主要风险",
            "诉讼",
            "承诺和或有事项",
        ),
    ),
    (
        "notes",
        (
            "notes to consolidated",
            "notes to financial statements",
            "significant accounting policies",
            "impairment",
            "contingencies",
            "附注",
            "会计政策",
            "减值",
        ),
    ),
    (
        "management_analysis",
        (
            "management's discussion",
            "management’s discussion",
            "management discussion",
            "operating review",
            "management analysis",
            "管理层讨论",
            "经营回顾",
        ),
    ),
    (
        "business_overview",
        (
            "business overview",
            "our business",
            "products and services",
            "主要业务",
            "业务概览",
        ),
    ),
)


def _flatten(value: Any) -> str:
    if isinstance(value, (list, tuple)):
        return " ".join(_flatten(item) for item in value)
    if isinstance(value, Mapping):
        return " ".join(f"{key} {_flatten(item)}" for key, item in value.items())
    return str(value or "")


def _search_text(chunk: Mapping[str, Any]) -> str:
    fields = (
        chunk.get("table_title"),
        chunk.get("table_context"),
        chunk.get("table_title_raw"),
        chunk.get("section_path"),
        chunk.get("group_key"),
        chunk.get("chunk_text"),
        chunk.get("search_text"),
        chunk.get("table_header"),
        chunk.get("raw_matrix"),
    )
    return " ".join(_flatten(value) for value in fields if value not in (None, "")).strip()


def _statement_family(text: str, chunk: Mapping[str, Any]) -> str:
    normalized = text.casefold()
    scores: dict[str, int] = {family: 0 for family, _ in _FAMILY_PATTERNS}
    for family, patterns in _FAMILY_PATTERNS:
        for pattern in patterns:
            if pattern.casefold() in normalized:
                scores[family] += max(1, len(pattern) // 8)

    # 表格行标签比“services”这类通用词更可靠；优先保留结构性财务表。
    if any(term in normalized for term in ("total assets", "total liabilities", "资产总额", "负债总额")):
        scores["balance_sheet"] += 20
    if any(term in normalized for term in ("cash generated", "cash used", "operating activities", "investing activities")):
        scores["cash_flow"] += 20
    if any(term in normalized for term in (
        "ratio analysis", "debt to equity", "gross margin percentage",
        "ebit margin", "earnings per share", "basic and diluted eps",
    )):
        scores["ratio"] += 20
    if any(term in normalized for term in ("risk factors", "principal risks", "risks and uncertainties", "market risk")):
        scores["risk"] += 20
    if any(term in normalized for term in ("geographic", "geographical", "by region", "europe", "greater china", "japan", "asia pacific")):
        scores["segment"] += 8
    if "total net sales" in normalized and any(
        term in normalized for term in ("gross margin", "operating income", "net income", "earnings per share")
    ):
        scores["income_statement"] += 30

    # 没有可识别的主题时，表格仍保留为 other，避免把普通披露误标成财务报表。
    best = max(scores, key=lambda family: (scores[family], -list(scores).index(family)))
    return best if scores[best] > 0 else "other"


def _statement_scope(text: str, family: str) -> str:
    normalized = text.casefold()
    if any(term in normalized for term in ("standalone", "separate financial", "parent company only", "独立口径", "单体")):
        return "standalone"
    if family == "segment":
        return "segment"
    if family in {"management_analysis", "business_overview", "risk"}:
        return "management_analysis"
    if any(term in normalized for term in ("consolidated", "合并")):
        return "consolidated"
    # 10-K/年报的主要财务报表在没有单体标记时按合并口径归类；
    # 其他文本保持 unknown，避免将叙述性段落误当成合并报表。
    if family in {"balance_sheet", "income_statement", "cash_flow", "equity", "ratio"}:
        return "consolidated"
    return "unknown"


def _period_end(text: str, fiscal_year: Any) -> str | None:
    match = None
    for candidate in _DATE_RE.finditer(text):
        prefix = text[max(0, candidate.start() - 60) : candidate.start()].casefold()
        if any(term in prefix for term in ("fiscal year ended", "year ended", "period ended", "as of", "balance as of")):
            match = candidate
            break
    if match:
        parsed = datetime.strptime(
            f"{match.group(1)} {match.group(2)} {match.group(3)}", "%B %d %Y"
        )
        return parsed.date().isoformat()
    try:
        year = int(fiscal_year)
    except (TypeError, ValueError):
        year = None
    if year is not None:
        return f"FY{year}"
    year_match = _YEAR_RE.search(text)
    return f"FY{year_match.group(0).replace(' ', '').upper().replace('FY', '')}" if year_match else None


def _unit(text: str, chunk: Mapping[str, Any]) -> str | None:
    match = _UNIT_RE.search(text)
    if match:
        return re.sub(r"\s+", " ", match.group(0)).strip()
    plain_match = re.search(r"\b(?:million|millions|billion|billions|thousand|thousands)\s+dollars?\b", text, re.IGNORECASE)
    if plain_match:
        return re.sub(r"\s+", " ", plain_match.group(0)).strip()
    currency = str(chunk.get("currency") or "").strip()
    if re.search(r"(?:₹|`|rs\.?)\s*crores?\b|\bcrores?\b", text, re.IGNORECASE):
        return f"{currency or 'INR'} crore"
    scale = str(chunk.get("unit_scale") or "").strip()
    if currency and scale and scale.casefold() != "as_reported":
        return f"{currency} {scale}"
    if currency:
        return f"{currency} as_reported"
    return scale or "not_disclosed"


def infer_semantic_metadata(chunk: Mapping[str, Any]) -> dict[str, Any]:
    """返回稳定的语义字段，结果可直接合并到 chunk/payload。"""

    text = _search_text(chunk)
    family = _statement_family(text, chunk)
    table_id = str(chunk.get("table_id") or "").strip()
    document_id = str(chunk.get("document_id") or "").strip()
    page = chunk.get("page_start")
    if table_id:
        table_group_id = table_id
    elif document_id and page is not None:
        table_group_id = f"{document_id}:page:{page}:text"
    else:
        table_group_id = str(chunk.get("chunk_id") or "") or None

    raw_title = chunk.get("table_title_raw") or chunk.get("table_title")
    if raw_title is None and table_id and chunk.get("group_key"):
        raw_title = str(chunk["group_key"])
    period_years = chunk.get("period_years")
    if not isinstance(period_years, list):
        period_years = sorted(
            {int(match.group(0).replace("FY", "").strip()) for match in _YEAR_RE.finditer(text)}
        )
    descriptor = " ".join(
        str(chunk.get(key) or "") for key in ("table_title", "table_context")
    ).casefold()
    row_labels = [str(value).strip() for value in chunk.get("row_labels", []) if str(value).strip()]
    region = row_labels[-1] if "geograph" in descriptor and row_labels else None
    explicit_scope = str(chunk.get("statement_scope") or "").strip()
    inferred_unit_scale = chunk.get("unit_scale")
    if re.search(r"(?:₹|`|rs\.?)\s*crores?\b|\bcrores?\b", text, re.IGNORECASE):
        inferred_unit_scale = "crore"
    return {
        "statement_family": family,
        "statement_scope": explicit_scope if explicit_scope not in {"", "unknown"} else _statement_scope(text, family),
        "period_end": _period_end(text, chunk.get("fiscal_year")),
        "period_years": period_years,
        "unit": _unit(text, chunk),
        "unit_scale": inferred_unit_scale,
        "region": region,
        "measure_name": chunk.get("measure_name"),
        "value_kind": chunk.get("value_kind"),
        "table_context": chunk.get("table_context"),
        "column_headers": chunk.get("column_headers", []),
        "parent_row_labels": chunk.get("parent_row_labels", []),
        "table_title_raw": str(raw_title).strip() if raw_title not in (None, "") else None,
        "table_group_id": table_group_id,
    }


def enrich_chunk(chunk: dict[str, Any]) -> dict[str, Any]:
    chunk.update(infer_semantic_metadata(chunk))
    return chunk
