"""指标/期间的保守字面覆盖探针；不是取数或语义正确性证明。"""
import re
from .comparative import requested_years

ALIASES = {
    '总净销售额': ('total net sales',), '营业利润': ('operating income', 'operating profit'),
    '净利润': ('net income', 'profit for the year'),
    '经营活动现金流': ('cash generated by operating activities', 'cash flows from operating activities', 'net cash generated from operating activities'),
    '购建固定资产现金支出': ('payments for acquisition of property', 'purchases of property', 'capital expenditures'),
    '收入': ('revenue', 'net sales'), '营业收入': ('revenue from operations', 'revenue'),
    '所得税费用': ('provision for income taxes', 'income tax expense'),
    '有效税率': ('effective tax rate',),
}


def metric_terms(metric):
    # 关系性描述不是原始报表标签；不要把未逐字命中误报为缺数据。
    if re.search(r'\b(?:impact|change|growth|estimated)\b|原因|影响|变化|增速', metric, re.I):
        return ()
    if metric.lower() == 'total operating income':
        return ()
    if metric in ALIASES:
        return ALIASES[metric]
    if re.fullmatch(r'[A-Za-z][A-Za-z ,/&()-]{2,100}', metric):
        return (metric.lower(),)
    return ()


def inspect_coverage(tasks, evidence, question):
    results = []
    for task in tasks:
        req = task.get('requirement') or {}
        task_text = ' '.join(str(req.get(k) or '') for k in ('topic', 'relation'))
        years = requested_years(task_text) or requested_years(question)
        sources = [e for e in evidence if task['task_id'] in e.retrieval_task_ids]
        for metric in req.get('metrics') or []:
            terms = metric_terms(str(metric))
            if not terms:
                results.append({'task_id': task['task_id'], 'metric': metric, 'status': 'unverified', 'missing_years': []})
                continue
            matched, present = [], set()
            for item in sources:
                text = item.text.lower()
                # 数值必须在指标附近，而不是仅凭文档年度或页码推断有数据。
                windows = [text[max(0, m.start()-30):m.end()+500]
                           for term in terms for m in re.finditer(re.escape(term), text)]
                if not any(re.search(r'\d', re.sub(r'(?<!\d)(?:19|20)\d{2}(?!\d)', '', w)) for w in windows):
                    continue
                matched.append(item.evidence_id)
                present.update(requested_years(text))
            missing = sorted(years - present)
            results.append({'task_id': task['task_id'], 'metric': metric, 'terms': list(terms),
                'evidence_ids': matched, 'requested_years': sorted(years), 'missing_years': missing,
                'status': 'candidate_covered' if matched and not missing else 'gap'})
    return results
