from __future__ import annotations

"""把既有召回层接到引用上下文和 LLM 生成层。"""

import re
import unicodedata
from time import perf_counter
from embeddings.retrieval_policy import identifiers, contains_identifiers, deduplicate
from .rerank import SemanticReranker
from .coverage import inspect_coverage
from typing import Any

from embeddings.contracts import QueryRequest
from embeddings.onnx_encoder import BGEEmbeddingEncoder
from embeddings.retrieve import QdrantRetriever, assemble_context
from embeddings.semantic_metadata import infer_semantic_metadata

from .llm import DeepSeekGenerator, DeepSeekPlanner, LLMRequestError, TextGenerator
from .prompts import (
    build_messages,
    build_planner_messages,
    validate_answer_facts,
    validate_citations,
)
from .schemas import Citation, Evidence, QueryBody, RAGResponse, RetrievalInfo
from .settings import Settings
from .comparative import segment_comparatives, is_segment_table, requested_years


NO_EVIDENCE_ANSWER = "当前年报证据不足以支持这个结论。请补充公司、财年或指标名称，或直接核对对应年报原文。"
VALIDATION_FAILURE_ANSWER = "当前回答的来源引用校验失败，请重试或核对来源原文。"
RISK_REFUSAL_ANSWER = "当前年报问答只解释已经披露的事实，不提供预测、交易或法律结论。请改问已披露的财务指标、风险因素或原文内容。"
CLARIFICATION_ANSWER = "这个问题需要先明确公司和财年；若要比较多家公司，请分别指定公司、财年和指标口径。"

_COMPANY_ALIASES: dict[str, tuple[str, ...]] = {
    "apple": ("apple", "苹果", "苹果公司"),
    "microsoft": ("microsoft", "微软", "微软公司"),
    "tcs": ("tcs", "塔塔咨询", "塔塔咨询服务", "塔塔咨询服务公司"),
}

_RISK_QUERY_MARKERS: tuple[tuple[str, str], ...] = (
    ("股价预测", "market_prediction"),
    ("目标价", "market_prediction"),
    ("买入", "investment_advice"),
    ("卖出", "investment_advice"),
    ("投资建议", "investment_advice"),
    ("法律意见", "legal_advice"),
    ("法律建议", "legal_advice"),
    ("赔付承诺", "commitment"),
    ("保证收益", "commitment"),
)

_QUERY_TERM_ALIASES: tuple[tuple[tuple[str, ...], tuple[str, ...]], ...] = (
    (("产品类别", "业务收入来源", "收入来源"), ("net sales disaggregated by significant products and services", "net sales by product category", "revenue by product line")),
    (("净销售额",), ("net sales", "total net sales")),
    (("现金流", "现金生成"), ("cash flow statement", "cash generated by operating activities", "cash flows from operating activities", "net cash generated from operating activities", "net cash from operations")),
    (("资产负债", "总资产", "总权益"), ("consolidated balance sheet", "total assets", "total liabilities", "total equity", "total stockholders equity")),
    (("损益", "总收入", "营业收入"), ("consolidated statement of profit and loss", "revenue from operations", "total income")),
    (("收入", "营收"), ("revenue", "revenue from operations", "total revenue")),
    (("利润", "盈利", "利润率"), ("profit for the year", "operating income", "net income", "operating margin")),
    (("每股", "EPS"), ("earnings per share", "basic and diluted EPS")),
    (("员工", "流失率"), ("employees", "total employees", "IT services attrition", "LTM attrition in IT services")),
    (("研发",), ("research and development expenses", "R&D")),
    (("所得税", "税率", "income tax", "effective tax"), ("income taxes", "effective tax rate", "one-time tax charge")),
    (("云业务", "云收入"), ("cloud revenue", "cloud services revenue")),
    (("风险", "不确定性"), ("risk factors", "principal risks", "risks and uncertainties", "market risk")),
)


class RAGService:
    def __init__(
        self,
        settings: Settings,
        *,
        retriever: QdrantRetriever | Any | None = None,
        generator: TextGenerator | None = None,
        planner: DeepSeekPlanner | Any | None = None,
    ) -> None:
        self.settings = settings
        self._retriever = retriever
        self._generator = generator
        self._planner = planner
        self._last_planner_meta: dict[str, Any] = {}
        self._last_retrieval_meta: dict[str, Any] = {}

    @property
    def retriever(self) -> QdrantRetriever | Any:
        if self._retriever is None:
            encoder = BGEEmbeddingEncoder(
                model_path=self.settings.embedding_model_path,
                tokenizer_path=self.settings.embedding_tokenizer_path,
                max_length=self.settings.embedding_max_length,
            )
            self._retriever = QdrantRetriever(
                qdrant_path=self.settings.qdrant_path,
                collection=self.settings.qdrant_collection,
                chunk_dir=self.settings.chunk_dir,
                encoder=encoder,
            )
        return self._retriever

    @property
    def generator(self) -> TextGenerator:
        if self._generator is None:
            self._generator = DeepSeekGenerator(self.settings)
        return self._generator

    @property
    def planner(self) -> DeepSeekPlanner:
        if self._planner is None:
            self._planner = DeepSeekPlanner(self.settings)
        return self._planner

    def _request(self, body: QueryBody) -> QueryRequest:
        return QueryRequest.from_mapping(body.model_dump(exclude_none=True))

    @staticmethod
    def _risk_refusal_reason(query: str) -> str | None:
        normalized = str(query or "").casefold()
        return next(
            (reason for marker, reason in _RISK_QUERY_MARKERS if marker in normalized),
            None,
        )

    def _clarification_reason(self, request: QueryRequest) -> str | None:
        """在检索前拦截无法唯一定位的公司/财年问题，避免自动猜测。"""

        normalized = str(request.query or "").casefold()
        mentioned = {
            company_id
            for company_id, aliases in _COMPANY_ALIASES.items()
            if any(alias.casefold() in normalized for alias in aliases)
        }
        if len(mentioned) > 1:
            return "multiple_companies"
        explicit = request.explicit_filters()
        explicit_company = explicit.get('company_id') or (next(iter(mentioned)) if mentioned else None)
        if explicit.get('document_id'):
            return None
        # 趋势问题允许在同一个问题中明确列出多个年份；其余问题需要一个
        # 可验证的财年，否则同一公司的连续年报会产生歧义。
        years = re.findall(r"(?:19|20)\d{2}", normalized)
        if not explicit_company:
            return "company_required"
        if not years and explicit.get('fiscal_year') is None and (
            not request.company_id
            or str(request.company_id).casefold() in _COMPANY_ALIASES
        ):
            return "fiscal_year_required"
        return None

    @staticmethod
    def _clarification_response(body: QueryBody, request: QueryRequest, reason: str) -> RAGResponse:
        return RAGResponse(
            answer=CLARIFICATION_ANSWER,
            answerable=False,
            citation_valid=False,
            citation_ids=[],
            citations=[],
            evidence=[],
            retrieval=RetrievalInfo(
                mode=body.mode,
                top_k=request.top_k,
                hit_count=0,
                resolved_filters=request.explicit_filters(),
                route="direct",
            ),
            generation={
                "provider": "none",
                "status": "clarification_needed",
                "refusal": {"gate": "request_scope", "reason": reason},
            },
        )

    @staticmethod
    def _validate_answer_output(answer: str, assembled: dict[str, Any]) -> dict[str, Any]:
        citation_check = validate_citations(answer, assembled)
        try:
            fact_check = validate_answer_facts(answer, assembled)
        except Exception as exc:
            fact_check = {"valid": None, "status": "failed", "error_type": type(exc).__name__}
        fact_check["validation_mode"] = "observe"
        return {
            "answer": answer if citation_check["valid"] else None,
            "status": "valid" if citation_check["valid"] else "invalid",
            "citation_check": citation_check,
            "fact_check": fact_check,
        }

    @staticmethod
    def _policy_refusal(body: QueryBody, request: QueryRequest, reason: str) -> RAGResponse:
        return RAGResponse(
            answer=RISK_REFUSAL_ANSWER,
            answerable=False,
            citation_valid=False,
            citation_ids=[],
            citations=[],
            evidence=[],
            retrieval=RetrievalInfo(
                mode=body.mode,
                top_k=request.top_k,
                hit_count=0,
                resolved_filters=request.explicit_filters(),
                route="direct",
            ),
            generation={
                "provider": "none",
                "status": "policy_refusal",
                "refusal": {"gate": "risk_type", "reason": reason},
            },
        )

    @staticmethod
    def _planner_candidate_top_k(request: QueryRequest) -> int:
        """自由问题扩大候选池，显式文档评测保持既有排序预算。"""

        if request.explicit_filters().get("document_id"):
            return min(max(request.top_k * 2, 10), 20)
        return min(max(request.top_k * 3, 12), 20)

    @staticmethod
    def _augment_task_queries(
        *,
        request_query: str,
        task: dict[str, Any],
    ) -> list[str]:
        """当 Planner 丢掉中文指标时，补回通用年报原文术语。"""

        requirement = task.get("requirement") or {}
        requirement_text = " ".join(
            str(value or "")
            for value in (
                requirement.get("topic"),
                " ".join(str(item) for item in requirement.get("metrics") or []),
                requirement.get("relation"),
            )
        )
        aliases: list[str] = []
        for markers, terms in _QUERY_TERM_ALIASES:
            if any(marker.casefold() in requirement_text.casefold() for marker in markers):
                aliases.extend(terms)
        # Planner 没有提供可识别主题时，才从原问题补充领域术语；否则会让
        # 收入、利润、现金流等并列任务共享同一条混合查询。
        if not aliases and not requirement_text.strip():
            for markers, terms in _QUERY_TERM_ALIASES:
                if any(marker.casefold() in request_query.casefold() for marker in markers):
                    aliases.extend(terms)
        queries = [str(value).strip() for value in task.get("queries") or [] if str(value).strip()]
        protected = identifiers(requirement_text)
        queries = [query for query in queries if contains_identifiers(query, protected)]
        if aliases:
            # 子任务必须保持独立，不能把整道复合题重新混入每条检索。
            seed = queries[0] if queries else requirement_text or request_query
            alias_query = f"{seed.strip()} {' '.join(dict.fromkeys(aliases))}".strip()
            if alias_query not in queries:
                # 领域原文术语优先进入融合排序，避免泛化中文查询的 dense 结果
                # 在 RRF 中稀释掉真正包含报表标签的表格/正文块。
                queries = [alias_query, *queries[:3]]
        growth_queries = []
        for metric in requirement.get('metrics') or []:
            match = re.fullmatch(r'(.+?)\s+(?:segment\s+)?revenue growth(?: rate)?', str(metric), re.I)
            if match:
                # 分别检索比较对象的原文增长表述，避免“X versus Y explanation”
                # 长查询只命中业务定义，而丢掉实际披露的增长数据。
                growth_queries.append(f'{match[1]} revenue grew increased')
        if growth_queries:
            queries = [*growth_queries[:2], *queries[:2]]
        return queries[:4] or [requirement_text.strip() or request_query.strip()]

    @classmethod
    def _augment_fallback_query(cls, query: str) -> str:
        """Planner 失败时仍保留中文问题，并补充年报英文标签。"""

        queries = cls._augment_task_queries(
            request_query=query,
            task={"requirement": {"topic": query}, "queries": []},
        )
        result = queries[0] if queries else query
        normalized = query.casefold()
        if result == query and any(marker in normalized for marker in ("财务表现", "经营表现", "整体表现")):
            result = (
                f"{query.strip()} revenue from operations operating margin "
                "cash flows from operating activities"
            )
        return result

    @classmethod
    def _fallback_needs_family_diversity(cls, query: str) -> bool:
        normalized = query.casefold()
        matched_groups = sum(
            any(marker.casefold() in normalized for marker in markers)
            for markers, _ in _QUERY_TERM_ALIASES
        )
        return matched_groups >= 2 or any(
            marker in normalized for marker in ("财务表现", "经营表现", "整体表现")
        )

    @staticmethod
    def _diversify_statement_families(hits: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """宽问题 fallback 先覆盖不同报表主题，再保持原始排名补齐。"""

        family_order: list[str] = []
        grouped: dict[str, list[dict[str, Any]]] = {}
        for hit in hits:
            family = str((hit.get("citation") or {}).get("statement_family") or "other")
            if family not in grouped:
                family_order.append(family)
                grouped[family] = []
            grouped[family].append(hit)

        first_by_family: list[dict[str, Any]] = []
        selected_ids: set[int] = set()
        financial_families = {"balance_sheet", "cash_flow", "income_statement", "equity", "ratio"}
        for family in family_order:
            candidates = grouped[family]
            chosen = candidates[0]
            if family in financial_families:
                chosen = next(
                    (
                        hit
                        for hit in candidates
                        if str((hit.get("citation") or {}).get("statement_scope") or "").casefold()
                        == "consolidated"
                    ),
                    chosen,
                )
            first_by_family.append(chosen)
            selected_ids.add(id(chosen))
        remaining = [hit for hit in hits if id(hit) not in selected_ids]
        return [*first_by_family, *remaining]

    @staticmethod
    def _normalize_match_text(value: Any) -> str:
        text = unicodedata.normalize("NFKC", str(value or "")).casefold()
        return re.sub(r"[^\w%]+", " ", text, flags=re.UNICODE).strip()

    @classmethod
    def _task_priority_phrases(cls, task: dict[str, Any]) -> list[str]:
        requirement = task.get("requirement") or {}
        requirement_text = " ".join(
            str(value or "")
            for value in (
                requirement.get("topic"),
                " ".join(str(item) for item in requirement.get("metrics") or []),
                requirement.get("relation"),
            )
        )
        values: list[str] = []
        for markers, terms in _QUERY_TERM_ALIASES:
            if any(marker.casefold() in requirement_text.casefold() for marker in markers):
                values.extend(terms)
        values.extend(str(item) for item in requirement.get("metrics") or [])
        for metric in requirement.get('metrics') or []:
            # 原文常把实体与指标写成“X ... revenue increased”，保留实体
            # 词组用于匹配，不能只要求“X revenue growth”整句字面出现。
            entity = re.sub(r'\b(?:segment|revenue|growth|operating|income|profit|margin|rate)\b', '', str(metric), flags=re.I).strip()
            if entity and entity != str(metric):
                values.append(entity)
        values.append(str(requirement.get("topic") or ""))

        phrases: list[str] = []
        for value in values:
            phrase = cls._normalize_match_text(value)
            if not phrase or phrase in phrases:
                continue
            ascii_tokens = re.findall(r"[a-z0-9%]+", phrase)
            if len(ascii_tokens) >= 2 or (len(ascii_tokens) == 1 and len(ascii_tokens[0]) >= 3):
                phrases.append(phrase)
        return phrases

    @classmethod
    def _structured_row_match(cls, text: str) -> tuple[str, bool]:
        row_line = next((line for line in text.splitlines() if "row_number=" in line.casefold()), "")
        if not row_line:
            return "", False
        parts = [part.strip() for part in re.split(r"[；;]", row_line) if part.strip()]
        fields = [part.split("=", 1) for part in parts if "=" in part]
        if len(fields) < 2:
            return "", False
        row_label = cls._normalize_match_text(fields[1][1])
        has_numeric_value = any(
            re.search(r"\d", value) is not None and value.strip().casefold() not in {"空值", "none", "null"}
            for _, value in fields[2:]
        )
        return row_label, has_numeric_value

    @classmethod
    def _prioritize_task_hits(
        cls,
        hits: list[dict[str, Any]],
        task: dict[str, Any],
    ) -> list[dict[str, Any]]:
        """用 Planner 指标和结构化行标签稳定任务内排序。"""

        phrases = cls._task_priority_phrases(task)
        if not phrases:
            return hits
        requirement = task.get("requirement") or {}
        prefers_group_coverage = bool(requirement.get("group_by"))
        explanation = " ".join(str(requirement.get(key) or "") for key in ("topic", "relation"))
        prefers_explanation = bool(re.search(r'原因|解释|一次性|归因|驱动|explain|reason|driver|one.time', explanation, re.I))

        ranked: list[tuple[tuple[int, int, int], int, dict[str, Any]]] = []
        for index, hit in enumerate(hits):
            payload = hit.get("payload") or {}
            raw_text = str(hit.get("text") or payload.get("search_text") or payload.get("chunk_text") or "")
            normalized_text = cls._normalize_match_text(raw_text)
            row_label, row_has_value = cls._structured_row_match(raw_text)
            row_hits = sum(phrase in row_label for phrase in phrases) if row_label else 0
            text_hits = sum(phrase in normalized_text for phrase in phrases)
            score = (
                (text_hits, row_hits, int(row_hits > 0 and row_has_value))
                if prefers_group_coverage or prefers_explanation
                else (row_hits, int(row_hits > 0 and row_has_value), text_hits)
            )
            if re.search(r'增速|增长|growth', str(requirement), re.I) and prefers_explanation:
                quantitative_growth = bool(re.search(r'\d\s*%', raw_text) and re.search(r'increas|grew|growth|declin|decreas', raw_text, re.I))
                score = (int(text_hits > 0 and quantitative_growth), text_hits, row_hits)
            ranked.append((score, index, hit))

        if not any(score != (0, 0, 0) for score, _, _ in ranked):
            return hits
        ranked.sort(key=lambda item: (-item[0][0], -item[0][1], -item[0][2], item[1]))
        return [hit for _, _, hit in ranked]

    @staticmethod
    def _evidence(hits: list[dict[str, Any]], assembled: dict[str, Any]) -> list[Evidence]:
        hit_by_id = {
            str(hit.get("chunk_id")): hit
            for hit in hits
            if hit.get("chunk_id") is not None
        }
        result: list[Evidence] = []
        for citation_data in assembled.get("citations") or []:
            chunk_id = str(citation_data.get("chunk_id") or "")
            hit = hit_by_id.get(chunk_id, {})
            text = str(
                hit.get("_context_text")
                or hit.get("text")
                or hit.get("payload", {}).get("chunk_text")
                or ""
            ).strip()
            if not text:
                continue
            payload = hit.get("payload") or {}
            semantic = infer_semantic_metadata(payload)
            citation_data = {
                **citation_data,
                **{
                    key: citation_data.get(key) or value
                    for key, value in semantic.items()
                    if key not in citation_data or citation_data.get(key) in (None, "")
                },
            }
            result.append(
                Evidence(
                    evidence_id=str(citation_data["evidence_id"]),
                    text=text,
                    citation=Citation(**citation_data),
                    retrieval_task_ids=list(hit.get("_retrieval_task_ids") or []),
                )
            )
        return result

    @staticmethod
    def _select_task_hits(
        task_groups: list[tuple[str, list[dict[str, Any]]]],
        *,
        limit: int,
    ) -> list[dict[str, Any]]:
        selected: list[dict[str, Any]] = []
        selected_by_id: dict[str, dict[str, Any]] = {}
        selected_by_text: dict[str, dict[str, Any]] = {}
        selected_by_table: dict[str, dict[str, Any]] = {}
        depth = 0
        while task_groups and len(selected) < limit:
            found = False
            for task_id, hits in task_groups:
                if depth >= len(hits):
                    continue
                found = True
                hit = hits[depth]
                payload = hit.get("payload") or {}
                citation = hit.get("citation") or {}
                chunk_id = str(hit.get("chunk_id") or payload.get("chunk_id") or "")
                if not chunk_id:
                    continue
                chunk_text = str(
                    hit.get("text") or payload.get("chunk_text") or ""
                ).strip()
                table_group_id = str(
                    citation.get("table_group_id")
                    or payload.get("table_group_id")
                    or payload.get("table_id")
                    or ""
                )
                has_full_table = bool(hit.get("_table_matrix") or payload.get("raw_matrix"))
                existing = (
                    selected_by_id.get(chunk_id)
                    or (selected_by_text.get(chunk_text) if chunk_text else None)
                    or (
                        selected_by_table.get(table_group_id)
                        if table_group_id and has_full_table
                        else None
                    )
                )
                if existing is not None:
                    task_ids = existing.setdefault("_retrieval_task_ids", [])
                    if task_id not in task_ids:
                        task_ids.append(task_id)
                    continue
                item = dict(hit)
                item["_retrieval_task_ids"] = [task_id]
                selected_by_id[chunk_id] = item
                if chunk_text:
                    selected_by_text[chunk_text] = item
                if table_group_id and has_full_table:
                    selected_by_table[table_group_id] = item
                selected.append(item)
                if len(selected) >= limit:
                    break
            if not found:
                break
            depth += 1
        for rank, hit in enumerate(selected, 1):
            hit["rank"] = rank
        return selected

    @staticmethod
    def _fuse_task_queries(
        query_results: list[list[dict[str, Any]]],
        *,
        rrf_k: int = 60,
        first_query_weight: float = 1.0,
    ) -> list[dict[str, Any]]:
        """在单个证据任务内融合多条查询，避免查询顺序决定最终候选。"""

        fused_by_id: dict[str, dict[str, Any]] = {}
        for query_index, current in enumerate(query_results):
            seen_in_query: set[str] = set()
            query_weight = first_query_weight if query_index == 0 else 1.0
            for rank, hit in enumerate(current, 1):
                chunk_id = str(hit.get("chunk_id") or (hit.get("payload") or {}).get("chunk_id") or "")
                if not chunk_id or chunk_id in seen_in_query:
                    continue
                seen_in_query.add(chunk_id)
                if chunk_id not in fused_by_id:
                    fused_by_id[chunk_id] = {
                        **hit,
                        "_task_query_rrf_score": 0.0,
                        "_task_query_match_count": 0,
                    }
                item = fused_by_id[chunk_id]
                item["_task_query_rrf_score"] += query_weight / (rrf_k + rank)
                item["_task_query_match_count"] += 1

        return sorted(
            fused_by_id.values(),
            key=lambda hit: (
                -float(hit.get("_task_query_rrf_score") or 0.0),
                -int(hit.get("_task_query_match_count") or 0),
                -float(hit.get("score") or 0.0),
                str(hit.get("chunk_id") or ""),
            ),
        )

    @staticmethod
    def _filter_task_scope(
        hits: list[dict[str, Any]],
        statement_scope: str | None,
        requirement: dict[str, Any] | None = None,
    ) -> list[dict[str, Any]]:
        """优先保留 Planner 指定的合并/单体口径；无匹配时不丢弃任务。"""

        requested = str(statement_scope or "").casefold().strip()
        topic_text = " ".join(
            str(value or "")
            for value in (
                (requirement or {}).get("topic"),
                " ".join(str(item) for item in (requirement or {}).get("metrics") or []),
            )
        ).casefold()
        # 分部、地区、员工和风险披露本身不是合并/单体财务报表口径，
        # 不能因为 Planner 默认填了“合并”而排除它们的有效证据。
        non_statement_topics = (
            "地区", "地域", "分部", "segment", "业务板块", "员工", "流失",
            "workforce", "attrition", "风险", "risk", "云业务", "cloud",
            "产品类别", "业务收入来源", "收入来源", "product category",
            "products and services",
            "所得税", "税率", "income tax", "effective tax", "会计估计", "使用寿命",
            "useful life", "财年长度", "财年周数", "fiscal weeks",
        )
        if any(marker in topic_text for marker in non_statement_topics):
            return hits
        scope_aliases = {
            "合并": "consolidated",
            "consolidated": "consolidated",
            "合并口径": "consolidated",
            "单体": "standalone",
            "独立": "standalone",
            "standalone": "standalone",
        }
        target = scope_aliases.get(requested)
        if not target:
            return hits
        scoped = [
            hit
            for hit in hits
            if str((hit.get("citation") or {}).get("statement_scope") or "").casefold()
            == target
        ]
        return scoped or hits

    def retrieve(self, body: QueryBody) -> tuple[QueryRequest, list[dict[str, Any]], dict[str, Any], list[Evidence]]:
        request = self._request(body)
        self._last_planner_meta = {}
        self._last_retrieval_meta = {}
        hits: list[dict[str, Any]] = []
        if not body.generate and not body.plan_retrieval:
            hits = self.retriever.search_request(request, mode=body.mode)
            self._last_retrieval_meta = dict(getattr(self.retriever, "last_search_meta", {}) or {})
            self._last_planner_meta = {
                "status": "not_needed",
                "route": "direct",
            }
        elif self.settings.planner_enabled:
            planner_meta: dict[str, Any] = {
                "status": "fallback",
                "route": "planner",
            }
            if self._planner is None and not self.settings.has_planner_key():
                planner_meta["reason"] = "planner_key_not_configured"
            else:
                try:
                    resolved = self.retriever.resolve_request(request)
                    filters = resolved.explicit_filters()
                    planner_started = perf_counter()
                    plan = self.planner.plan(
                        build_planner_messages(
                            question=request.query,
                            company_id=str(filters.get("company_id") or "") or None,
                            fiscal_year=(
                                int(filters["fiscal_year"])
                                if filters.get("fiscal_year") is not None
                                else None
                            ),
                            document_id=str(filters.get("document_id") or "") or None,
                        )
                    )
                    task_groups: list[tuple[str, list[dict[str, Any]]]] = []
                    planner_ms = round((perf_counter() - planner_started) * 1000, 3)
                    retrieval_tasks: list[dict[str, Any]] = []
                    candidate_count = 0
                    original_started = perf_counter()
                    original_hits = self.retriever.search_request(QueryRequest(query=request.query,
                        top_k=self._planner_candidate_top_k(request), filters=filters), mode=body.mode)
                    original_meta = dict(getattr(self.retriever, 'last_search_meta', {}) or {})
                    task_groups.append(('ORIGINAL', original_hits))
                    candidate_count += len(original_hits)
                    original_ms = round((perf_counter() - original_started) * 1000, 3)
                    for index, task in enumerate(plan["retrieval_tasks"], 1):
                        task_id = f"T{index}"
                        query_results: list[list[dict[str, Any]]] = []
                        query_meta: list[dict[str, Any]] = []
                        queries = self._augment_task_queries(
                            request_query=request.query,
                            task=task,
                        )
                        protected = identifiers(request.query)
                        if protected:
                            queries = [q + ' ' + ' '.join(x for x in protected if not contains_identifiers(q, [x])) for q in queries]
                        queries = list(dict.fromkeys(q.strip() for q in queries))
                        candidate_top_k = self._planner_candidate_top_k(request)
                        for subquery in queries:
                            current = self.retriever.search_request(
                                QueryRequest(query=subquery, top_k=candidate_top_k, filters=filters),
                                mode=body.mode,
                            )
                            query_results.append(current)
                            query_meta.append(dict(getattr(self.retriever, "last_search_meta", {}) or {}))
                            candidate_count += len(current)
                        task_hits = self._fuse_task_queries(
                            query_results,
                            # _augment_task_queries 将任务专用英文标签放在首位；
                            # 仅在服务层对这类首条查询加权，保持通用融合函数等权且
                            # 与查询输入顺序无关的既有契约。
                            first_query_weight=4.0 if len(queries) > 1 else 1.0,
                        )
                        task_hits = self._filter_task_scope(
                            task_hits,
                            task.get("statement_scope"),
                            task.get("requirement"),
                        )
                        task_hits = self._prioritize_task_hits(task_hits, task)
                        payloads = getattr(getattr(self.retriever, 'bm25', None), 'payloads', {})
                        supplements = segment_comparatives(payloads, task, filters, request.query)
                        basis = None
                        if supplements:
                            extra = []
                            for payload in supplements:
                                hit = self.retriever._with_citation({'payload': payload, 'score': 0.0})
                                hit['citation']['context_chunk_ids'] = payload['context_chunk_ids']
                                hit['citation']['comparison_years'] = payload['comparison_years']
                                extra.append(hit)
                            wanted = requested_years(request.query)
                            if wanted and set(supplements[0]['comparison_years']) == wanted:
                                basis = {'document_id': supplements[0]['document_id'], 'years': sorted(wanted),
                                         'rule': '全部跨年分部计算使用此文档可比列，含CAGR起点年；其他原报值仅用于显式对照。'}
                                task_hits = [h for h in task_hits if not is_segment_table(str(h.get('text') or '')) or
                                             (h.get('citation') or {}).get('document_id') == basis['document_id']]
                            extra_ids = {h['chunk_id'] for h in extra}
                            task_hits = extra + [h for h in task_hits if h.get('chunk_id') not in extra_ids]
                        task_groups.append((task_id, task_hits))
                        retrieval_tasks.append(
                            {
                                "task_id": task_id,
                                "requirement": task["requirement"],
                                "queries": queries,
                                "statement_scope": task.get("statement_scope") or "",
                                "candidate_chunk_ids": [hit.get("chunk_id") for hit in task_hits],
                                "candidate_top_k": candidate_top_k,
                                "query_retrieval": query_meta,
                                "comparison_basis": basis,
                                "supplemented_chunk_ids": [p['chunk_id'] for p in supplements],
                            }
                        )
                    hits = self._select_task_hits(
                        task_groups,
                        # 每个任务至少保留三个候选，避免并列主题中精确表格
                        # 排在第三位时被两路候选配额提前截断。
                        limit=min(max(request.top_k, 4 * len(task_groups)), 40),
                    )
                    hits, duplicate_meta = deduplicate(hits)
                    semantic_meta = {'status': 'not_available'}
                    if isinstance(self._retriever, QdrantRetriever):
                        hits, semantic_meta = SemanticReranker(self.settings).rank(request.query, hits)
                    self._last_retrieval_meta = {
                        "candidate_count": candidate_count,
                        "effective_top_k": len(hits),
                        "coverage_truncated": candidate_count > len(hits),
                        'original_query': {'elapsed_ms': original_ms, 'query': request.query, 'retrieval': original_meta},
                        'semantic_rerank': semantic_meta, 'duplicates': duplicate_meta,
                        'planner_ms': planner_ms,
                    }
                    planner_meta = {
                        "status": "used",
                        "route": "planner",
                        "intent": plan.get("intent"),
                        "entities": plan.get("entities", []),
                        "time_scope": plan.get("time_scope"),
                        "retrieval_tasks": retrieval_tasks,
                        "needs_calculation": plan.get("needs_calculation", False),
                        "clarification_needed": plan.get("clarification_needed", False),
                        "usage": dict(getattr(self.planner, "last_usage", {}) or {}),
                        "finish_reason": getattr(self.planner, "last_finish_reason", None),
                        'original_query': self._last_retrieval_meta['original_query'],
                        'semantic_rerank': semantic_meta,
                        'planner_ms': planner_ms,
                    }
                except (LLMRequestError, ValueError, TypeError) as exc:
                    planner_meta.update(
                        {
                            "reason": type(exc).__name__,
                            "error": str(exc),
                        }
                    )
            if planner_meta["status"] != "used":
                fallback_request = QueryRequest(
                    query=request.query,
                    top_k=max(request.top_k, 40),
                    filters=request.explicit_filters(),
                )
                hits = self.retriever.search_request(fallback_request, mode=body.mode)
                if self._fallback_needs_family_diversity(request.query):
                    hits = self._diversify_statement_families(hits)
                self._last_retrieval_meta = dict(getattr(self.retriever, "last_search_meta", {}) or {})
                planner_meta["fallback_top_k"] = fallback_request.top_k
            self._last_planner_meta = planner_meta
        else:
            hits = self.retriever.search_request(request, mode=body.mode)
            self._last_retrieval_meta = dict(getattr(self.retriever, "last_search_meta", {}) or {})
            self._last_planner_meta = {
                "status": "disabled",
                "route": "planner",
            }
        assembled = assemble_context(hits, max_chars=self.settings.retrieval_max_context_chars)
        evidence = self._evidence(hits, assembled)
        evidence_ids_by_task: dict[str, list[str]] = {}
        for item in evidence:
            for task_id in item.retrieval_task_ids:
                evidence_ids_by_task.setdefault(task_id, []).append(item.evidence_id)
        for task in self._last_planner_meta.get("retrieval_tasks") or []:
            task["evidence_ids"] = evidence_ids_by_task.get(str(task.get("task_id")), [])
        missing_tasks = [t for t in self._last_planner_meta.get('retrieval_tasks', []) if not t['evidence_ids']]
        coverage_before = inspect_coverage(self._last_planner_meta.get('retrieval_tasks', []), evidence, request.query)
        metric_gaps = [row for row in coverage_before if row['status'] == 'gap'] if self.settings.coverage_probe_mode == 'repair' else []
        repair_log = []
        retry_jobs = []
        scope = self.retriever.resolve_request(request).explicit_filters()
        for gap in metric_gaps:
            years = gap['missing_years'] or gap['requested_years']
            query = ' '.join([str(scope.get('company_id') or ''), ' '.join(map(str, years)), gap['terms'][0]])
            retry_jobs.append({'task_id': gap['task_id'], 'query': query, 'metric': gap['metric']})
        for task in missing_tasks:
            retry_jobs.append({'task_id': task['task_id'], 'query': (task.get('queries') or [request.query])[0]})
        seen_jobs = set()
        for job in retry_jobs:
            if len(repair_log) >= 4:
                break
            task_id, query = job['task_id'], job['query']
            if (task_id, query) in seen_jobs:
                continue
            seen_jobs.add((task_id, query))
            retry = self.retriever.search_request(QueryRequest(query=query, top_k=3, filters=scope), mode=body.mode)
            for hit in retry:
                hit['_retrieval_task_ids'] = [task_id]
            repair_log.append({**job, 'candidate_ids': [h.get('chunk_id') for h in retry]})
            hits = retry + hits
        if repair_log:
            hits, _ = deduplicate(hits)
            assembled = assemble_context(hits, max_chars=self.settings.retrieval_max_context_chars)
            evidence = self._evidence(hits, assembled)
            for task in self._last_planner_meta.get('retrieval_tasks', []):
                task['evidence_ids'] = [e.evidence_id for e in evidence if task['task_id'] in e.retrieval_task_ids]
        self._last_planner_meta['coverage_check'] = {'repair_attempts': repair_log,
            'mode': self.settings.coverage_probe_mode,
            'metrics_before': coverage_before,
            'metrics_after': inspect_coverage(self._last_planner_meta.get('retrieval_tasks', []), evidence, request.query),
            'missing_task_ids': [t['task_id'] for t in self._last_planner_meta.get('retrieval_tasks', []) if not t.get('evidence_ids')],
            'boundary': '指标附近数值及证据年份为覆盖线索；candidate_covered不证明行列、单位或语义正确，unverified须核对'}
        self._last_retrieval_meta['context'] = {'chars': len(assembled.get('context', '')),
            'budget': self.settings.retrieval_max_context_chars, 'evidence_count': len(evidence),
            'selected_chunk_ids': [e.citation.chunk_id for e in evidence]}
        return request, hits, assembled, evidence

    def _top_dense_score(self, hits: list[dict[str, Any]], mode: str) -> float | None:
        if not hits:
            return None
        if mode == "dense":
            return float(hits[0].get("score"))
        values = [float(h['dense_score']) for h in hits if h.get('dense_score') is not None]
        return max(values) if values else None

    def _retrieval_info(self, *, request: QueryRequest, hits: list[dict[str, Any]], mode: str) -> RetrievalInfo:
        resolved = self.retriever.resolve_request(request)
        meta = dict(self._last_retrieval_meta)
        if not meta and hits:
            meta = dict(hits[0].get("_retrieval_meta") or {})
        return RetrievalInfo(
            mode=mode,
            top_k=request.top_k,
            effective_top_k=int(meta["effective_top_k"]) if meta.get("effective_top_k") is not None else None,
            hit_count=len(hits),
            resolved_filters=resolved.explicit_filters(),
            top_score=float(hits[0]["score"]) if hits else None,
            top_dense_score=self._top_dense_score(hits, mode),
            candidate_count=int(meta.get("candidate_count", len(hits))),
            coverage_truncated=bool(meta.get("coverage_truncated", False)),
            route=str(self._last_planner_meta.get("route") or meta.get("route") or "planner"),
            retrieval_tasks=list(self._last_planner_meta.get("retrieval_tasks") or []),
            planner=dict(self._last_planner_meta),
            diagnostics=meta,
        )

    def query(self, body: QueryBody) -> RAGResponse:
        request_for_policy = self._request(body)
        risk_reason = self._risk_refusal_reason(request_for_policy.query)
        if risk_reason:
            return self._policy_refusal(body, request_for_policy, risk_reason)
        clarification_reason = self._clarification_reason(request_for_policy)
        if clarification_reason:
            return self._clarification_response(body, request_for_policy, clarification_reason)
        request, hits, assembled, evidence = self.retrieve(body)
        retrieval = self._retrieval_info(request=request, hits=hits, mode=body.mode)
        enough_evidence = bool(evidence)
        if retrieval.top_dense_score is not None and body.mode in {"dense", "hybrid"}:
            enough_evidence = enough_evidence and retrieval.top_dense_score >= self.settings.no_answer_dense_threshold

        citations = [item.citation for item in evidence]
        base_generation = {
            "provider": self.settings.llm_provider if body.generate else "none",
            "model": self.settings.deepseek_model if body.generate else None,
            "status": "not_requested",
            "usage": dict(getattr(self._generator, "last_usage", {}) or {}) if body.generate else {},
        }
        if not enough_evidence:
            base_generation["status"] = "no_evidence"
            base_generation["refusal"] = {
                "gate": "evidence",
                "reason": "insufficient_retrieval_evidence",
            }
            return RAGResponse(
                answer=NO_EVIDENCE_ANSWER,
                answerable=False,
                citation_valid=False,
                citation_ids=[],
                citations=citations,
                evidence=evidence,
                retrieval=retrieval,
                generation=base_generation,
            )

        if not body.generate:
            base_generation["status"] = "retrieval_only"
            return RAGResponse(
                answer="已完成规划与召回，未生成答案。" if body.plan_retrieval else "已完成召回，当前请求未调用 LLM。",
                answerable=True,
                citation_valid=True,
                citation_ids=[item.evidence_id for item in evidence],
                citations=citations,
                evidence=evidence,
                retrieval=retrieval,
                generation=base_generation,
            )

        messages = build_messages(
            question=request.query,
            assembled=assembled,
            planner_meta=self._last_planner_meta,
        )
        answer = self.generator.generate(messages)
        checked = self._validate_answer_output(answer, assembled)
        citation_check = checked["citation_check"]
        base_generation.update({
            "status": "generated" if citation_check["valid"] else "answer_validation_failed",
            "selected_output": "single" if citation_check["valid"] else "none",
            "usage": self._combined_usage(dict(getattr(self._generator, "last_usage", {}) or {})),
            "finish_reason": getattr(self._generator, "last_finish_reason", None),
            "citation_check": citation_check,
            "fact_check": checked["fact_check"],
        })
        if not citation_check["valid"]:
            base_generation["refusal"] = {"gate": "citation_validation", "reason": "invalid_citation"}
        return RAGResponse(
            answer=answer if citation_check["valid"] else VALIDATION_FAILURE_ANSWER,
            answerable=bool(citation_check["valid"]),
            citation_valid=bool(citation_check["valid"]),
            citation_ids=citation_check["citation_ids"],
            citations=citations,
            evidence=evidence,
            retrieval=retrieval,
            generation=base_generation,
        )

    @staticmethod
    def _combined_usage(*calls: dict[str, Any]) -> dict[str, Any]:
        fields = (
            "prompt_tokens",
            "completion_tokens",
            "total_tokens",
            "prompt_cache_hit_tokens",
            "prompt_cache_miss_tokens",
        )
        result = {
            field: sum(int(call.get(field) or 0) for call in calls)
            for field in fields
            if any(call.get(field) is not None for call in calls)
        }
        hit = result.get("prompt_cache_hit_tokens")
        miss = result.get("prompt_cache_miss_tokens")
        if hit is not None or miss is not None:
            hit = int(hit or 0)
            miss = int(miss or 0)
            result["prompt_cache_total_tokens"] = hit + miss
            result["prompt_cache_hit_ratio"] = round(hit / max(hit + miss, 1), 4)
        return result

    def close(self) -> None:
        if self._retriever is not None and hasattr(self._retriever, "close"):
            self._retriever.close()
