from __future__ import annotations

"""把既有召回层接到引用上下文和 LLM 生成层。"""

import re
import unicodedata
from typing import Any

from embeddings.contracts import QueryRequest
from embeddings.onnx_encoder import BGEEmbeddingEncoder
from embeddings.retrieve import QdrantRetriever, assemble_context
from embeddings.semantic_metadata import infer_semantic_metadata

from .llm import DeepSeekGenerator, DeepSeekPlanner, LLMRequestError, TextGenerator
from .prompts import (
    build_messages,
    build_planner_messages,
    build_review_messages,
    validate_citations,
)
from .schemas import Citation, Evidence, QueryBody, RAGResponse, RetrievalInfo
from .settings import Settings


NO_EVIDENCE_ANSWER = "根据当前召回内容无法确定。"

_QUERY_TERM_ALIASES: tuple[tuple[tuple[str, ...], tuple[str, ...]], ...] = (
    (("产品类别", "业务收入来源", "收入来源"), ("net sales disaggregated by significant products and services", "net sales by product category", "revenue by product line")),
    (("净销售额",), ("net sales", "total net sales")),
    (("现金流", "现金生成"), ("cash flow statement", "cash generated by operating activities", "cash flows from operating activities", "net cash generated from operating activities", "net cash from operations")),
    (("资产负债", "总资产", "总权益"), ("consolidated balance sheet", "total assets", "total liabilities", "total equity", "total stockholders equity")),
    (("损益", "总收入", "营业收入"), ("consolidated statement of profit and loss", "revenue from operations", "total income")),
    (("收入", "营收"), ("revenue", "revenue from operations", "total revenue")),
    (("利润", "盈利", "利润率"), ("profit for the year", "operating income", "net income", "operating margin")),
    (("每股", "EPS"), ("earnings per share", "basic and diluted EPS")),
    (("员工", "流失率"), ("employees", "total employees", "IT services attrition", "LTM attrition in IT services")),
    (("研发",), ("research and development expenses", "R&D")),
    (("云业务", "云收入"), ("cloud revenue", "cloud services revenue")),
    (("风险", "不确定性"), ("risk factors", "principal risks", "risks and uncertainties", "market risk")),
)


class RAGService:
    def __init__(
        self,
        settings: Settings,
        *,
        retriever: QdrantRetriever | Any | None = None,
        generator: TextGenerator | None = None,
        planner: DeepSeekPlanner | Any | None = None,
    ) -> None:
        self.settings = settings
        self._retriever = retriever
        self._generator = generator
        self._planner = planner
        self._last_planner_meta: dict[str, Any] = {}
        self._last_retrieval_meta: dict[str, Any] = {}

    @property
    def retriever(self) -> QdrantRetriever | Any:
        if self._retriever is None:
            encoder = BGEEmbeddingEncoder(
                model_path=self.settings.embedding_model_path,
                tokenizer_path=self.settings.embedding_tokenizer_path,
                max_length=self.settings.embedding_max_length,
            )
            self._retriever = QdrantRetriever(
                qdrant_path=self.settings.qdrant_path,
                collection=self.settings.qdrant_collection,
                chunk_dir=self.settings.chunk_dir,
                encoder=encoder,
            )
        return self._retriever

    @property
    def generator(self) -> TextGenerator:
        if self._generator is None:
            self._generator = DeepSeekGenerator(self.settings)
        return self._generator

    @property
    def planner(self) -> DeepSeekPlanner:
        if self._planner is None:
            self._planner = DeepSeekPlanner(self.settings)
        return self._planner

    def _request(self, body: QueryBody) -> QueryRequest:
        return QueryRequest.from_mapping(body.model_dump(exclude_none=True))

    @staticmethod
    def _planner_candidate_top_k(request: QueryRequest) -> int:
        """自由问题扩大候选池，显式文档评测保持既有排序预算。"""

        if request.explicit_filters().get("document_id"):
            return min(max(request.top_k * 2, 10), 20)
        return min(max(request.top_k * 3, 12), 20)

    @staticmethod
    def _augment_task_queries(
        *,
        request_query: str,
        task: dict[str, Any],
    ) -> list[str]:
        """当 Planner 丢掉中文指标时，补回通用年报原文术语。"""

        requirement = task.get("requirement") or {}
        requirement_text = " ".join(
            str(value or "")
            for value in (
                requirement.get("topic"),
                " ".join(str(item) for item in requirement.get("metrics") or []),
                requirement.get("relation"),
            )
        )
        aliases: list[str] = []
        for markers, terms in _QUERY_TERM_ALIASES:
            if any(marker.casefold() in requirement_text.casefold() for marker in markers):
                aliases.extend(terms)
        # Planner 没有提供可识别主题时，才从原问题补充领域术语；否则会让
        # 收入、利润、现金流等并列任务共享同一条混合查询。
        if not aliases:
            for markers, terms in _QUERY_TERM_ALIASES:
                if any(marker.casefold() in request_query.casefold() for marker in markers):
                    aliases.extend(terms)
        queries = [str(value).strip() for value in task.get("queries") or [] if str(value).strip()]
        if aliases:
            alias_query = f"{request_query.strip()} {' '.join(dict.fromkeys(aliases))}".strip()
            if alias_query not in queries:
                # 领域原文术语优先进入融合排序，避免泛化中文查询的 dense 结果
                # 在 RRF 中稀释掉真正包含报表标签的表格/正文块。
                queries = [alias_query, *queries[:3]]
        return queries[:4] or [request_query.strip()]

    @classmethod
    def _augment_fallback_query(cls, query: str) -> str:
        """Planner 失败时仍保留中文问题，并补充年报英文标签。"""

        queries = cls._augment_task_queries(
            request_query=query,
            task={"requirement": {"topic": query}, "queries": []},
        )
        result = queries[0] if queries else query
        normalized = query.casefold()
        if result == query and any(marker in normalized for marker in ("财务表现", "经营表现", "整体表现")):
            result = (
                f"{query.strip()} revenue from operations operating margin "
                "cash flows from operating activities"
            )
        return result

    @classmethod
    def _fallback_needs_family_diversity(cls, query: str) -> bool:
        normalized = query.casefold()
        matched_groups = sum(
            any(marker.casefold() in normalized for marker in markers)
            for markers, _ in _QUERY_TERM_ALIASES
        )
        return matched_groups >= 2 or any(
            marker in normalized for marker in ("财务表现", "经营表现", "整体表现")
        )

    @staticmethod
    def _diversify_statement_families(hits: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """宽问题 fallback 先覆盖不同报表主题，再保持原始排名补齐。"""

        family_order: list[str] = []
        grouped: dict[str, list[dict[str, Any]]] = {}
        for hit in hits:
            family = str((hit.get("citation") or {}).get("statement_family") or "other")
            if family not in grouped:
                family_order.append(family)
                grouped[family] = []
            grouped[family].append(hit)

        first_by_family: list[dict[str, Any]] = []
        selected_ids: set[int] = set()
        financial_families = {"balance_sheet", "cash_flow", "income_statement", "equity", "ratio"}
        for family in family_order:
            candidates = grouped[family]
            chosen = candidates[0]
            if family in financial_families:
                chosen = next(
                    (
                        hit
                        for hit in candidates
                        if str((hit.get("citation") or {}).get("statement_scope") or "").casefold()
                        == "consolidated"
                    ),
                    chosen,
                )
            first_by_family.append(chosen)
            selected_ids.add(id(chosen))
        remaining = [hit for hit in hits if id(hit) not in selected_ids]
        return [*first_by_family, *remaining]

    @staticmethod
    def _normalize_match_text(value: Any) -> str:
        text = unicodedata.normalize("NFKC", str(value or "")).casefold()
        return re.sub(r"[^\w%]+", " ", text, flags=re.UNICODE).strip()

    @classmethod
    def _task_priority_phrases(cls, task: dict[str, Any]) -> list[str]:
        requirement = task.get("requirement") or {}
        requirement_text = " ".join(
            str(value or "")
            for value in (
                requirement.get("topic"),
                " ".join(str(item) for item in requirement.get("metrics") or []),
                requirement.get("relation"),
            )
        )
        values: list[str] = []
        for markers, terms in _QUERY_TERM_ALIASES:
            if any(marker.casefold() in requirement_text.casefold() for marker in markers):
                values.extend(terms)
        values.extend(str(item) for item in requirement.get("metrics") or [])
        values.append(str(requirement.get("topic") or ""))

        phrases: list[str] = []
        for value in values:
            phrase = cls._normalize_match_text(value)
            if not phrase or phrase in phrases:
                continue
            ascii_tokens = re.findall(r"[a-z0-9%]+", phrase)
            if len(ascii_tokens) >= 2 or (len(ascii_tokens) == 1 and len(ascii_tokens[0]) >= 3):
                phrases.append(phrase)
        return phrases

    @classmethod
    def _structured_row_match(cls, text: str) -> tuple[str, bool]:
        row_line = next((line for line in text.splitlines() if "row_number=" in line.casefold()), "")
        if not row_line:
            return "", False
        parts = [part.strip() for part in re.split(r"[；;]", row_line) if part.strip()]
        fields = [part.split("=", 1) for part in parts if "=" in part]
        if len(fields) < 2:
            return "", False
        row_label = cls._normalize_match_text(fields[1][1])
        has_numeric_value = any(
            re.search(r"\d", value) is not None and value.strip().casefold() not in {"空值", "none", "null"}
            for _, value in fields[2:]
        )
        return row_label, has_numeric_value

    @classmethod
    def _prioritize_task_hits(
        cls,
        hits: list[dict[str, Any]],
        task: dict[str, Any],
    ) -> list[dict[str, Any]]:
        """用 Planner 指标和结构化行标签稳定任务内排序。"""

        phrases = cls._task_priority_phrases(task)
        if not phrases:
            return hits
        requirement = task.get("requirement") or {}
        prefers_group_coverage = bool(requirement.get("group_by"))

        ranked: list[tuple[tuple[int, int, int], int, dict[str, Any]]] = []
        for index, hit in enumerate(hits):
            payload = hit.get("payload") or {}
            raw_text = str(hit.get("text") or payload.get("search_text") or payload.get("chunk_text") or "")
            normalized_text = cls._normalize_match_text(raw_text)
            row_label, row_has_value = cls._structured_row_match(raw_text)
            row_hits = sum(phrase in row_label for phrase in phrases) if row_label else 0
            text_hits = sum(phrase in normalized_text for phrase in phrases)
            score = (
                (text_hits, row_hits, int(row_hits > 0 and row_has_value))
                if prefers_group_coverage
                else (row_hits, int(row_hits > 0 and row_has_value), text_hits)
            )
            ranked.append((score, index, hit))

        if not any(score != (0, 0, 0) for score, _, _ in ranked):
            return hits
        ranked.sort(key=lambda item: (-item[0][0], -item[0][1], -item[0][2], item[1]))
        return [hit for _, _, hit in ranked]

    @staticmethod
    def _evidence(hits: list[dict[str, Any]], assembled: dict[str, Any]) -> list[Evidence]:
        hit_by_id = {
            str(hit.get("chunk_id")): hit
            for hit in hits
            if hit.get("chunk_id") is not None
        }
        result: list[Evidence] = []
        for citation_data in assembled.get("citations") or []:
            chunk_id = str(citation_data.get("chunk_id") or "")
            hit = hit_by_id.get(chunk_id, {})
            text = str(
                hit.get("_context_text")
                or hit.get("text")
                or hit.get("payload", {}).get("chunk_text")
                or ""
            ).strip()
            if not text:
                continue
            payload = hit.get("payload") or {}
            semantic = infer_semantic_metadata(payload)
            citation_data = {
                **citation_data,
                **{
                    key: citation_data.get(key) or value
                    for key, value in semantic.items()
                    if key not in citation_data or citation_data.get(key) in (None, "")
                },
            }
            result.append(
                Evidence(
                    evidence_id=str(citation_data["evidence_id"]),
                    text=text,
                    citation=Citation(**citation_data),
                    retrieval_task_ids=list(hit.get("_retrieval_task_ids") or []),
                )
            )
        return result

    @staticmethod
    def _select_task_hits(
        task_groups: list[tuple[str, list[dict[str, Any]]]],
        *,
        limit: int,
    ) -> list[dict[str, Any]]:
        selected: list[dict[str, Any]] = []
        selected_by_id: dict[str, dict[str, Any]] = {}
        selected_by_text: dict[str, dict[str, Any]] = {}
        selected_by_table: dict[str, dict[str, Any]] = {}
        depth = 0
        while task_groups and len(selected) < limit:
            found = False
            for task_id, hits in task_groups:
                if depth >= len(hits):
                    continue
                found = True
                hit = hits[depth]
                payload = hit.get("payload") or {}
                citation = hit.get("citation") or {}
                chunk_id = str(hit.get("chunk_id") or payload.get("chunk_id") or "")
                if not chunk_id:
                    continue
                chunk_text = str(
                    hit.get("text") or payload.get("chunk_text") or ""
                ).strip()
                table_group_id = str(
                    citation.get("table_group_id")
                    or payload.get("table_group_id")
                    or payload.get("table_id")
                    or ""
                )
                has_full_table = bool(hit.get("_table_matrix") or payload.get("raw_matrix"))
                existing = (
                    selected_by_id.get(chunk_id)
                    or (selected_by_text.get(chunk_text) if chunk_text else None)
                    or (
                        selected_by_table.get(table_group_id)
                        if table_group_id and has_full_table
                        else None
                    )
                )
                if existing is not None:
                    task_ids = existing.setdefault("_retrieval_task_ids", [])
                    if task_id not in task_ids:
                        task_ids.append(task_id)
                    continue
                item = dict(hit)
                item["_retrieval_task_ids"] = [task_id]
                selected_by_id[chunk_id] = item
                if chunk_text:
                    selected_by_text[chunk_text] = item
                if table_group_id and has_full_table:
                    selected_by_table[table_group_id] = item
                selected.append(item)
                if len(selected) >= limit:
                    break
            if not found:
                break
            depth += 1
        for rank, hit in enumerate(selected, 1):
            hit["rank"] = rank
        return selected

    @staticmethod
    def _fuse_task_queries(
        query_results: list[list[dict[str, Any]]],
        *,
        rrf_k: int = 60,
        first_query_weight: float = 1.0,
    ) -> list[dict[str, Any]]:
        """在单个证据任务内融合多条查询，避免查询顺序决定最终候选。"""

        fused_by_id: dict[str, dict[str, Any]] = {}
        for query_index, current in enumerate(query_results):
            seen_in_query: set[str] = set()
            query_weight = first_query_weight if query_index == 0 else 1.0
            for rank, hit in enumerate(current, 1):
                chunk_id = str(hit.get("chunk_id") or (hit.get("payload") or {}).get("chunk_id") or "")
                if not chunk_id or chunk_id in seen_in_query:
                    continue
                seen_in_query.add(chunk_id)
                if chunk_id not in fused_by_id:
                    fused_by_id[chunk_id] = {
                        **hit,
                        "_task_query_rrf_score": 0.0,
                        "_task_query_match_count": 0,
                    }
                item = fused_by_id[chunk_id]
                item["_task_query_rrf_score"] += query_weight / (rrf_k + rank)
                item["_task_query_match_count"] += 1

        return sorted(
            fused_by_id.values(),
            key=lambda hit: (
                -float(hit.get("_task_query_rrf_score") or 0.0),
                -int(hit.get("_task_query_match_count") or 0),
                -float(hit.get("score") or 0.0),
                str(hit.get("chunk_id") or ""),
            ),
        )

    @staticmethod
    def _filter_task_scope(
        hits: list[dict[str, Any]],
        statement_scope: str | None,
        requirement: dict[str, Any] | None = None,
    ) -> list[dict[str, Any]]:
        """优先保留 Planner 指定的合并/单体口径；无匹配时不丢弃任务。"""

        requested = str(statement_scope or "").casefold().strip()
        topic_text = " ".join(
            str(value or "")
            for value in (
                (requirement or {}).get("topic"),
                " ".join(str(item) for item in (requirement or {}).get("metrics") or []),
            )
        ).casefold()
        # 分部、地区、员工和风险披露本身不是合并/单体财务报表口径，
        # 不能因为 Planner 默认填了“合并”而排除它们的有效证据。
        non_statement_topics = (
            "地区", "地域", "分部", "segment", "业务板块", "员工", "流失",
            "workforce", "attrition", "风险", "risk", "云业务", "cloud",
            "产品类别", "业务收入来源", "收入来源", "product category",
            "products and services",
        )
        if any(marker in topic_text for marker in non_statement_topics):
            return hits
        scope_aliases = {
            "合并": "consolidated",
            "consolidated": "consolidated",
            "合并口径": "consolidated",
            "单体": "standalone",
            "独立": "standalone",
            "standalone": "standalone",
        }
        target = scope_aliases.get(requested)
        if not target:
            return hits
        scoped = [
            hit
            for hit in hits
            if str((hit.get("citation") or {}).get("statement_scope") or "").casefold()
            == target
        ]
        return scoped or hits

    def retrieve(self, body: QueryBody) -> tuple[QueryRequest, list[dict[str, Any]], dict[str, Any], list[Evidence]]:
        request = self._request(body)
        self._last_planner_meta = {}
        self._last_retrieval_meta = {}
        hits: list[dict[str, Any]] = []
        if not body.generate:
            hits = self.retriever.search_request(request, mode=body.mode)
            self._last_retrieval_meta = dict(getattr(self.retriever, "last_search_meta", {}) or {})
            self._last_planner_meta = {
                "status": "not_needed",
                "route": "direct",
            }
        elif self.settings.planner_enabled:
            planner_meta: dict[str, Any] = {
                "status": "fallback",
                "route": "planner",
            }
            if self._planner is None and not self.settings.has_planner_key():
                planner_meta["reason"] = "planner_key_not_configured"
            else:
                try:
                    resolved = self.retriever.resolve_request(request)
                    filters = resolved.explicit_filters()
                    plan = self.planner.plan(
                        build_planner_messages(
                            question=request.query,
                            company_id=str(filters.get("company_id") or "") or None,
                            fiscal_year=(
                                int(filters["fiscal_year"])
                                if filters.get("fiscal_year") is not None
                                else None
                            ),
                            document_id=str(filters.get("document_id") or "") or None,
                        )
                    )
                    task_groups: list[tuple[str, list[dict[str, Any]]]] = []
                    retrieval_tasks: list[dict[str, Any]] = []
                    candidate_count = 0
                    for index, task in enumerate(plan["retrieval_tasks"], 1):
                        task_id = f"T{index}"
                        query_results: list[list[dict[str, Any]]] = []
                        query_meta: list[dict[str, Any]] = []
                        queries = self._augment_task_queries(
                            request_query=request.query,
                            task=task,
                        )
                        candidate_top_k = self._planner_candidate_top_k(request)
                        for subquery in queries:
                            current = self.retriever.search_request(
                                QueryRequest(query=subquery, top_k=candidate_top_k, filters=filters),
                                mode=body.mode,
                            )
                            query_results.append(current)
                            query_meta.append(dict(getattr(self.retriever, "last_search_meta", {}) or {}))
                            candidate_count += len(current)
                        task_hits = self._fuse_task_queries(
                            query_results,
                            # _augment_task_queries 将任务专用英文标签放在首位；
                            # 仅在服务层对这类首条查询加权，保持通用融合函数等权且
                            # 与查询输入顺序无关的既有契约。
                            first_query_weight=4.0 if len(queries) > 1 else 1.0,
                        )
                        task_hits = self._filter_task_scope(
                            task_hits,
                            task.get("statement_scope"),
                            task.get("requirement"),
                        )
                        task_hits = self._prioritize_task_hits(task_hits, task)
                        task_groups.append((task_id, task_hits))
                        retrieval_tasks.append(
                            {
                                "task_id": task_id,
                                "requirement": task["requirement"],
                                "queries": queries,
                                "statement_scope": task.get("statement_scope") or "",
                                "candidate_chunk_ids": [hit.get("chunk_id") for hit in task_hits],
                                "candidate_top_k": candidate_top_k,
                                "query_retrieval": query_meta,
                            }
                        )
                    hits = self._select_task_hits(
                        task_groups,
                        # 每个任务至少保留三个候选，避免并列主题中精确表格
                        # 排在第三位时被两路候选配额提前截断。
                        limit=min(max(request.top_k, 3 * len(task_groups)), 12),
                    )
                    self._last_retrieval_meta = {
                        "candidate_count": candidate_count,
                        "effective_top_k": len(hits),
                        "coverage_truncated": candidate_count > len(hits),
                    }
                    planner_meta = {
                        "status": "used",
                        "route": "planner",
                        "intent": plan.get("intent"),
                        "entities": plan.get("entities", []),
                        "time_scope": plan.get("time_scope"),
                        "retrieval_tasks": retrieval_tasks,
                        "needs_calculation": plan.get("needs_calculation", False),
                        "clarification_needed": plan.get("clarification_needed", False),
                        "usage": dict(getattr(self.planner, "last_usage", {}) or {}),
                        "finish_reason": getattr(self.planner, "last_finish_reason", None),
                    }
                except (LLMRequestError, ValueError, TypeError) as exc:
                    planner_meta.update(
                        {
                            "reason": type(exc).__name__,
                            "error": str(exc),
                        }
                    )
            if planner_meta["status"] != "used":
                fallback_request = QueryRequest(
                    query=self._augment_fallback_query(request.query),
                    top_k=max(request.top_k, 40),
                    filters=request.explicit_filters(),
                )
                hits = self.retriever.search_request(fallback_request, mode=body.mode)
                if self._fallback_needs_family_diversity(request.query):
                    hits = self._diversify_statement_families(hits)
                self._last_retrieval_meta = dict(getattr(self.retriever, "last_search_meta", {}) or {})
                planner_meta["fallback_top_k"] = fallback_request.top_k
            self._last_planner_meta = planner_meta
        else:
            hits = self.retriever.search_request(request, mode=body.mode)
            self._last_retrieval_meta = dict(getattr(self.retriever, "last_search_meta", {}) or {})
            self._last_planner_meta = {
                "status": "disabled",
                "route": "planner",
            }
        assembled = assemble_context(hits, max_chars=self.settings.retrieval_max_context_chars)
        evidence = self._evidence(hits, assembled)
        evidence_ids_by_task: dict[str, list[str]] = {}
        for item in evidence:
            for task_id in item.retrieval_task_ids:
                evidence_ids_by_task.setdefault(task_id, []).append(item.evidence_id)
        for task in self._last_planner_meta.get("retrieval_tasks") or []:
            task["evidence_ids"] = evidence_ids_by_task.get(str(task.get("task_id")), [])
        return request, hits, assembled, evidence

    def _top_dense_score(self, hits: list[dict[str, Any]], mode: str) -> float | None:
        if not hits:
            return None
        if mode == "dense":
            return float(hits[0].get("score"))
        value = hits[0].get("dense_score")
        return float(value) if value is not None else None

    def _retrieval_info(self, *, request: QueryRequest, hits: list[dict[str, Any]], mode: str) -> RetrievalInfo:
        resolved = self.retriever.resolve_request(request)
        meta = dict(self._last_retrieval_meta)
        if not meta and hits:
            meta = dict(hits[0].get("_retrieval_meta") or {})
        return RetrievalInfo(
            mode=mode,
            top_k=request.top_k,
            effective_top_k=int(meta["effective_top_k"]) if meta.get("effective_top_k") is not None else None,
            hit_count=len(hits),
            resolved_filters=resolved.explicit_filters(),
            top_score=float(hits[0]["score"]) if hits else None,
            top_dense_score=self._top_dense_score(hits, mode),
            candidate_count=int(meta.get("candidate_count", len(hits))),
            coverage_truncated=bool(meta.get("coverage_truncated", False)),
            route=str(self._last_planner_meta.get("route") or meta.get("route") or "planner"),
            retrieval_tasks=list(self._last_planner_meta.get("retrieval_tasks") or []),
            planner=dict(self._last_planner_meta),
        )

    def query(self, body: QueryBody) -> RAGResponse:
        request, hits, assembled, evidence = self.retrieve(body)
        retrieval = self._retrieval_info(request=request, hits=hits, mode=body.mode)
        enough_evidence = bool(evidence)
        if retrieval.top_dense_score is not None and body.mode in {"dense", "hybrid"}:
            enough_evidence = enough_evidence and retrieval.top_dense_score >= self.settings.no_answer_dense_threshold

        citations = [item.citation for item in evidence]
        base_generation = {
            "provider": self.settings.llm_provider if body.generate else "none",
            "model": self.settings.deepseek_model if body.generate else None,
            "status": "not_requested",
            "usage": dict(getattr(self._generator, "last_usage", {}) or {}) if body.generate else {},
        }
        if not enough_evidence:
            base_generation["status"] = "no_evidence"
            return RAGResponse(
                answer=NO_EVIDENCE_ANSWER,
                answerable=False,
                citation_valid=False,
                citation_ids=[],
                citations=citations,
                evidence=evidence,
                retrieval=retrieval,
                generation=base_generation,
            )

        if not body.generate:
            base_generation["status"] = "retrieval_only"
            return RAGResponse(
                answer="已完成召回，当前请求未调用 LLM。",
                answerable=True,
                citation_valid=True,
                citation_ids=[item.evidence_id for item in evidence],
                citations=citations,
                evidence=evidence,
                retrieval=retrieval,
                generation=base_generation,
            )

        messages = build_messages(
            question=request.query,
            assembled=assembled,
            planner_meta=self._last_planner_meta,
        )
        try:
            draft = self.generator.generate(messages)
        except LLMRequestError:
            base_generation["status"] = "draft_generation_failed"
            raise

        draft_usage = dict(getattr(self._generator, "last_usage", {}) or {})
        draft_finish_reason = getattr(self._generator, "last_finish_reason", None)
        draft_citation_check = validate_citations(draft, assembled)
        draft_meta = {
            "status": "generated",
            "usage": draft_usage,
            "finish_reason": draft_finish_reason,
            "citation_check": draft_citation_check,
        }
        review_messages = build_review_messages(
            question=request.query,
            draft=draft,
            assembled=assembled,
            planner_meta=self._last_planner_meta,
        )
        try:
            answer = self.generator.generate(review_messages)
        except LLMRequestError:
            base_generation.update(
                {
                    "status": "review_generation_failed",
                    "draft": draft_meta,
                    "review": {"status": "failed"},
                }
            )
            if draft_citation_check["valid"]:
                base_generation.update(
                    {
                        "status": "generated_from_draft_review_failed",
                        "selected_output": "draft",
                        "citation_check": draft_citation_check,
                    }
                )
                return RAGResponse(
                    answer=draft,
                    answerable=True,
                    citation_valid=True,
                    citation_ids=draft_citation_check["citation_ids"],
                    citations=citations,
                    evidence=evidence,
                    retrieval=retrieval,
                    generation=base_generation,
                )
            return RAGResponse(
                answer="模型回答复核失败，未安全展示生成内容。",
                answerable=False,
                citation_valid=False,
                citation_ids=[],
                citations=citations,
                evidence=evidence,
                retrieval=retrieval,
                generation=base_generation,
            )

        review_usage = dict(getattr(self._generator, "last_usage", {}) or {})
        review_finish_reason = getattr(self._generator, "last_finish_reason", None)
        review_citation_check = validate_citations(answer, assembled)
        base_generation.update(
            {
                "usage": self._combined_usage(draft_usage, review_usage),
                "draft": draft_meta,
                "review": {
                    "status": "generated",
                    "usage": review_usage,
                    "finish_reason": review_finish_reason,
                    "citation_check": review_citation_check,
                },
            }
        )
        if not review_citation_check["valid"] and draft_citation_check["valid"]:
            base_generation.update(
                {
                    "status": "generated_from_draft_review_invalid",
                    "selected_output": "draft",
                    "citation_check": draft_citation_check,
                    "review_unknown_ids": review_citation_check["unknown_ids"],
                }
            )
            return RAGResponse(
                answer=draft,
                answerable=True,
                citation_valid=True,
                citation_ids=draft_citation_check["citation_ids"],
                citations=citations,
                evidence=evidence,
                retrieval=retrieval,
                generation=base_generation,
            )
        if not review_citation_check["valid"]:
            base_generation["status"] = "citation_validation_failed"
            base_generation["selected_output"] = "none"
            base_generation["unknown_ids"] = review_citation_check["unknown_ids"]
            base_generation["citation_check"] = review_citation_check
            return RAGResponse(
                answer="模型返回的答案未通过引用校验，未安全展示生成内容。",
                answerable=False,
                citation_valid=False,
                citation_ids=review_citation_check["citation_ids"],
                citations=citations,
                evidence=evidence,
                retrieval=retrieval,
                generation=base_generation,
            )

        base_generation["status"] = "generated"
        base_generation["selected_output"] = "review"
        base_generation["citation_check"] = review_citation_check
        return RAGResponse(
            answer=answer,
            answerable=True,
            citation_valid=True,
            citation_ids=review_citation_check["citation_ids"],
            citations=citations,
            evidence=evidence,
            retrieval=retrieval,
            generation=base_generation,
        )

    @staticmethod
    def _combined_usage(*calls: dict[str, Any]) -> dict[str, Any]:
        fields = (
            "prompt_tokens",
            "completion_tokens",
            "total_tokens",
            "prompt_cache_hit_tokens",
            "prompt_cache_miss_tokens",
        )
        result = {
            field: sum(int(call.get(field) or 0) for call in calls)
            for field in fields
            if any(call.get(field) is not None for call in calls)
        }
        hit = result.get("prompt_cache_hit_tokens")
        miss = result.get("prompt_cache_miss_tokens")
        if hit is not None or miss is not None:
            hit = int(hit or 0)
            miss = int(miss or 0)
            result["prompt_cache_total_tokens"] = hit + miss
            result["prompt_cache_hit_ratio"] = round(hit / max(hit + miss, 1), 4)
        return result

    def close(self) -> None:
        if self._retriever is not None and hasattr(self._retriever, "close"):
            self._retriever.close()
