"""冻结小样本问题与证据判据，对比检索通道；不生成答案、不改写标签。"""
import json
import sys
import time
from pathlib import Path
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from rag_api.rerank import SemanticReranker
from rag_api.settings import Settings
from rag_api.llm import DeepSeekPlanner
from rag_api.prompts import build_planner_messages
from rag_api.service import RAGService

CASES = [
    ('apple_revenue_exact', 'exact_label', 'apple', 2024, 'Apple FY2024 total net sales', ['total net sales'], ['391,035']),
    ('apple_revenue_natural', 'natural_language', 'apple', 2024, '苹果FY2024一整年总共卖了多少钱？', ['total net sales'], ['391,035']),
    ('ms_profit_exact', 'exact_label', 'microsoft', 2023, 'Microsoft FY2023 operating income', ['operating income'], ['88,523']),
    ('ms_profit_natural', 'natural_language', 'microsoft', 2023, '微软FY2023经营业务本身赚了多少利润？', ['operating income'], ['88,523']),
    ('apple_cash_exact', 'exact_label', 'apple', 2024, 'Apple FY2024 cash generated by operating activities', ['operating activities'], ['118,254']),
    ('apple_cash_natural', 'natural_language', 'apple', 2024, '苹果FY2024经营活动实际带来了多少现金？', ['operating activities'], ['118,254']),
    ('tcs_assets_exact', 'exact_label', 'tcs', 2024, 'TCS FY2024 consolidated total assets', ['total assets'], ['146,449']),
    ('tcs_assets_natural', 'natural_language', 'tcs', 2024, 'TCS FY2024合并口径家底总额是多少？', ['total assets'], ['146,449']),
    ('tcs_cash_exact', 'exact_label', 'tcs', 2024, 'TCS FY2024 net cash generated from operating activities', ['net cash generated from operating activities'], ['44,338']),
    ('tcs_cash_natural', 'natural_language', 'tcs', 2024, 'TCS FY2024经营活动最终净流入多少现金？', ['net cash generated from operating activities'], ['44,338']),
    ('apple_tax_exact', 'exact_label', 'apple', 2024, 'Apple FY2024 provision for income taxes', ['provision for income taxes'], ['29,749']),
    ('apple_tax_natural', 'natural_language', 'apple', 2024, '苹果FY2024利润表计提了多少所得税？', ['provision for income taxes'], ['29,749']),
]


def relevant(text, terms, values):
    return all(term.lower() in text.lower() for term in terms) and all(v.replace(',', '') in text.replace(',', '') for v in values)


def main():
    # 标签在发起检索之前从固定原文判据生成；保留ID供人工复核。
    chunks = [json.loads(line) for path in (ROOT / 'data/processed/annual_reports/v1_single_company_chunks').glob('*.chunks.jsonl')
              for line in path.read_text(encoding='utf-8').splitlines()]
    labels = {}
    for name, group, company, year, question, terms, values in CASES:
        labels[name] = [p['chunk_id'] for p in chunks if p.get('company_id') == company and p.get('fiscal_year') == year
                        and relevant(str(p.get('chunk_text') or ''), terms, values)]
        if not labels[name]:
            raise ValueError(f'No ground truth candidates: {name}')
    output = ROOT / 'data/evaluation/hybrid_module_eval_expanded.json'
    results = []
    for name, group, company, year, question, terms, values in CASES:
        for mode in ('dense', 'bm25', 'hybrid'):
            started = time.perf_counter()
            request = Request('http://127.0.0.1:3000/api/rag/query', data=json.dumps({
                'query': question, 'company_id': company, 'fiscal_year': year, 'generate': False,
                'top_k': 10, 'mode': mode}).encode(), headers={'Content-Type': 'application/json'})
            with urlopen(request, timeout=180) as response:
                result = json.load(response)
            hits = result['evidence']
            ranks = [i for i, h in enumerate(hits, 1) if h['citation']['chunk_id'] in labels[name]]
            rank = min(ranks, default=0)
            row = {'case': name, 'group': group, 'mode': mode, 'first_relevant_rank': rank,
                   'hit_at_5': bool(rank and rank <= 5), 'mrr_at_10': 1/rank if rank else 0,
                   'elapsed_ms': round((time.perf_counter()-started)*1000, 2),
                   'request_id': result['generation'].get('request_id'), 'diagnostics': result['retrieval'].get('diagnostics')}
            results.append(row)
            if mode == 'hybrid':
                candidates = [{'chunk_id': h['citation']['chunk_id'], 'text': h['text'], 'citation': h['citation']} for h in hits]
                ranked, meta = SemanticReranker(Settings()).rank(question, candidates)
                ranks = [i for i, h in enumerate(ranked, 1) if h['chunk_id'] in labels[name]]
                rank = min(ranks, default=0)
                results.append({**row, 'mode': 'hybrid_semantic', 'first_relevant_rank': rank,
                                'hit_at_5': bool(rank and rank <= 5), 'mrr_at_10': 1/rank if rank else 0,
                                'elapsed_ms': row['elapsed_ms'] + meta.get('elapsed_ms', 0),
                                'semantic': meta})
            print(name, mode, row['first_relevant_rank'], flush=True)
            output.write_text(json.dumps({'status': 'in_progress', 'gold_chunk_ids': labels,
                'results': results, 'cases': CASES}, ensure_ascii=False, indent=2), encoding='utf-8')
    summary = {}
    # 对同一冻结标签测查询规划并集，不调用回答生成。
    for name, group, company, year, question, terms, values in CASES:
        begin = time.perf_counter()
        planner = DeepSeekPlanner(Settings())
        try:
            plan = planner.plan(build_planner_messages(question=question, company_id=company, fiscal_year=year))
        except Exception as exc:
            output.write_text(json.dumps({'status': 'incomplete', 'failed_case': name,
                'error': str(exc), 'gold_chunk_ids': labels, 'results': results, 'cases': CASES},
                ensure_ascii=False, indent=2), encoding='utf-8')
            raise
        queries = [question]
        for task in plan['retrieval_tasks']:
            queries.extend(RAGService._augment_task_queries(request_query=question, task=task))
        combined = {}
        for query in list(dict.fromkeys(queries))[:6]:
            request = Request('http://127.0.0.1:3000/api/rag/query', data=json.dumps({
                'query': query, 'company_id': company, 'fiscal_year': year, 'generate': False,
                'top_k': 10, 'mode': 'hybrid'}).encode(), headers={'Content-Type': 'application/json'})
            with urlopen(request, timeout=180) as response:
                response = json.load(response)
            for hit in response['evidence']:
                cid = hit['citation']['chunk_id']
                combined[cid] = {'chunk_id': cid, 'text': hit['text'], 'citation': hit['citation']}
        ranked, meta = SemanticReranker(Settings()).rank(question, list(combined.values())[:20])
        ranks = [i for i,h in enumerate(ranked[:10], 1) if h['chunk_id'] in labels[name]]
        rank = min(ranks, default=0)
        results.append({'case': name, 'group': group, 'mode': 'planned_union', 'first_relevant_rank': rank,
                        'hit_at_5': bool(rank and rank <=5), 'mrr_at_10': 1/rank if rank else 0,
                        'semantic': meta, 'elapsed_ms': round((time.perf_counter()-begin)*1000,2), 'queries': queries})
        print(name, 'planned_union', rank, flush=True)
    for mode in ('dense', 'bm25', 'hybrid', 'hybrid_semantic', 'planned_union'):
        summary[mode] = {}
        for group in ('all', 'exact_label', 'natural_language'):
            rows = [r for r in results if r['mode'] == mode and (group == 'all' or r['group'] == group)]
            summary[mode][group] = {'n': len(rows), 'hit_at_5': sum(r['hit_at_5'] for r in rows)/len(rows),
                                   'mrr_at_10': sum(r['mrr_at_10'] for r in rows)/len(rows)}
    report = {'label_method': '预先固定公司/年度/原文术语和数值判据；本地代理标签，未经双人标注，不是线上准确率',
              'cases': CASES, 'gold_chunk_ids': labels, 'results': results, 'summary': summary}
    output.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')
    print(json.dumps(summary, ensure_ascii=False))


if __name__ == '__main__':
    main()
